#!/usr/bin/env bash
#
# Build tests for AVR ATmega2560
#

# exit on first failure
set -e

#
# Backup pins_TRIGORILLA_14.h
#
cp Marlin/src/pins/ramps/pins_TRIGORILLA_14.h Marlin/src/pins/ramps/pins_TRIGORILLA_14.h.backup

#
# Build with the default configurations
#
restore_configs
exec_test $1 $2 "Default Configuration"

#
# Test with DwinTFT code disabled
#
opt_disable DWIN_TFT DWIN_TFT_DEBUG EXTENSIBLE_UI
exec_test $1 $2 "Test with DwinTFT code disabled"


######## Example Configurations ##############
#
# Test 4MaxPro with BLTouch
#
restore_configs
use_example_configs Anycubic4MaxPro/A4MaxProBLTouch
exec_test $1 $2 "Test 4MaxPro BLTouch"

# clean up
restore_configs
